In [ ]:
from google.colab import files
files.upload()

Saving financial_plan.csv to financial_plan (1).csv

{'financial_plan (1).csv': b'ProductID,Product_name,Plan_2023_units,Plan_2024_units,Plan_2025_units,Plan_2023_PLN,Plan_2024_PLN,Plan_2025_PLN,Price_PLN_per_unit\r\nP001,Product 001,486,695,543,10021.32,14330.9,11196.66,20.62\r\nP002,Product 002,347,376,360,3480.41,3771.28,3610.8,10.03\r\nP003,Product 003,599,849,818,21569.99,30572.49,29456.18,36.01\r\nP004,Product 004,1024,1920,1693,28897.28,54182.4,47776.46,28.22\r\nP005,Product 005,333,406,321,28151.82,34323.24,27137.34,84.54\r\nP006,Product 006,452,748,479,16113.8,26666.2,17076.35,35.65\r\nP007,Product 007,928,965,992,14198.4,14764.5,15177.6,15.3\r\nP008,Product 008,1644,2023,1105,14154.84,17418.03,9514.05,8.61\r\nP009,Product 009,998,1182,872,45059.7,53367.3,39370.8,45.15\r\nP010,Product 010,890,1084,1163,19989.4,24346.64,26120.98,22.46\r\nP011,Product 011,740,687,541,19950.4,18521.52,14585.36,26.96\r\nP012,Product 012,904,868,1069,16326.24,15676.08,19306.14,18.06\r\nP013,Product 013,1760,1370,1879,14080,10960,15032,8\r\nP014,Product 014,326,341,334,18363.58,19208.53,18814.22,56.33\r\nP015,Product 015,1310,1167,1240,53644.5,47788.65,50778,40.95\r\nP016,Product 016,672,844,917,22619.52,28409.04,30866.22,33.66\r\nP017,Product 017,521,600,640,24434.9,28140,30016,46.9\r\nP018,Product 018,361,367,391,4043.2,4110.4,4379.2,11.2\r\nP019,Product 019,434,374,443,54158.86,46671.46,55281.97,124.79\r\nP020,Product 020,1807,2394,1964,40549.08,53721.36,44072.16,22.44\r\nP021,Product 021,547,637,507,20419.51,23779.21,18926.31,37.33\r\nP022,Product 022,428,353,411,21348.64,17607.64,20500.68,49.88\r\nP023,Product 023,663,563,709,5304,4504,5672,8\r\nP024,Product 024,469,529,521,46965.66,52974.06,52172.94,100.14\r\nP025,Product 025,887,936,711,26370.51,27827.28,21138.03,29.73\r\nP026,Product 026,1832,2216,1649,14656,17728,13192,8\r\nP027,Product 027,470,629,610,10217.8,13674.46,13261.4,21.74\r\nP028,Product 028,764,646,867,168698.84,142643.26,191442.27,220.81\r\nP029,Product 029,375,432,381,8936.25,10294.56,9079.23,23.83\r\nP030,Product 030,2248,2243,2069,22030.4,21981.4,20276.2,9.8\r\nP031,Product 031,1123,1147,1265,28288.37,28892.93,31865.35,25.19\r\nP032,Product 032,476,429,398,18111.8,16323.45,15143.9,38.05\r\nP033,Product 033,1175,1254,1236,21032.5,22446.6,22124.4,17.9\r\nP034,Product 034,1681,1599,1423,30476.53,28989.87,25798.99,18.13\r\nP035,Product 035,789,1045,855,54535.68,72230.4,59097.6,69.12\r\nP036,Product 036,274,358,454,14593.24,19067.08,24180.04,53.26\r\nP037,Product 037,2874,1898,3373,81564.12,53865.24,95725.74,28.38\r\nP038,Product 038,1317,1581,1985,35638.02,42781.86,53714.1,27.06\r\nP039,Product 039,1526,1499,1662,48542.06,47683.19,52868.22,31.81\r\nP040,Product 040,964,770,763,19848.76,15854.3,15710.17,20.59\r\nP041,Product 041,560,691,811,15842.4,19548.39,22943.19,28.29\r\nP042,Product 042,738,1251,793,23306.04,39506.58,25042.94,31.58\r\nP043,Product 043,1429,1577,1367,123294.12,136063.56,117944.76,86.28\r\nP044,Product 044,867,1118,1050,10299.96,13281.84,12474,11.88\r\nP045,Product 045,493,400,420,28441.17,23076,24229.8,57.69\r\nP046,Product 046,856,853,1093,85548.64,85248.82,109234.42,99.94\r\nP047,Product 047,2383,2546,2764,35721.17,38164.54,41432.36,14.99\r\nP048,Product 048,1034,594,1161,33884.18,19465.38,38045.97,32.77\r\nP049,Product 049,1004,950,852,34567.72,32708.5,29334.36,34.43\r\nP050,Product 050,412,354,313,10398.88,8934.96,7900.12,25.24\r\nP051,Product 051,362,405,268,7207.42,8063.55,5335.88,19.91\r\nP052,Product 052,654,609,636,8809.38,8203.23,8566.92,13.47\r\nP053,Product 053,632,609,686,5056,4872,5488,8\r\nP054,Product 054,753,775,830,33011.52,33976,36387.2,43.84\r\nP055,Product 055,811,875,826,6488,7000,6608,8\r\nP056,Product 056,2745,2408,2415,114658.65,100582.16,100874.55,41.77\r\nP057,Product 057,830,767,758,46986.3,43419.87,42910.38,56.61\r\nP058,Product 058,1666,1620,1663,21891.24,21286.8,21851.82,13.14\r\nP059,Product 059,821,765,804,35688.87,33254.55,34949.88,43.47\r\nP060,Product 060,2059,2127,2028,100335.07,103648.71,98824.44,48.73\r\nP061,Product 061,415,418,455,20239.55,20385.86,22190.35,48.77\r\nP062,Product 062,430,658,707,8780.6,13436.36,14436.94,20.42\r\nP063,Product 063,1168,1930,1536,43297.76,71545.1,56939.52,37.07\r\nP064,Product 064,750,698,945,24885,23159.64,31355.1,33.18\r\nP065,Product 065,1378,1312,1483,21427.9,20401.6,23060.65,15.55\r\nP066,Product 066,1291,1544,1048,24787.2,29644.8,20121.6,19.2\r\nP067,Product 067,1258,1266,1012,58346.04,58717.08,46936.56,46.38\r\nP068,Product 068,1206,1372,1516,22926.06,26081.72,28819.16,19.01\r\nP069,Product 069,1023,1010,1295,40879.08,40359.6,51748.2,39.96\r\nP070,Product 070,2110,2214,1876,64566,67748.4,57405.6,30.6\r\nP071,Product 071,1235,1536,1089,29528.85,36725.76,26037.99,23.91\r\nP072,Product 072,1146,1359,1336,35594.76,42210.54,41496.16,31.06\r\nP073,Product 073,751,1065,1305,27644.31,39202.65,48037.05,36.81\r\nP074,Product 074,619,590,457,18625.71,17753.1,13751.13,30.09\r\nP075,Product 075,498,606,519,16284.6,19816.2,16971.3,32.7\r\nP076,Product 076,1384,1027,1254,66293.6,49193.3,60066.6,47.9\r\nP077,Product 077,312,403,291,7865.52,10159.63,7336.11,25.21\r\nP078,Product 078,448,512,512,15008,17152,17152,33.5\r\nP079,Product 079,638,442,430,15784.12,10935.08,10638.2,24.74\r\nP080,Product 080,899,755,946,34998.07,29392.15,36827.78,38.93\r\nP081,Product 081,386,421,407,10117.06,11034.41,10667.47,26.21\r\nP082,Product 082,2797,1879,2362,137080.97,92089.79,115761.62,49.01\r\nP083,Product 083,1121,1141,1375,73885.11,75203.31,90626.25,65.91\r\nP084,Product 084,2951,3150,2761,29746.08,31752,27830.88,10.08\r\nP085,Product 085,1604,1439,1408,131287.4,117782.15,115244.8,81.85\r\nP086,Product 086,1492,1018,1518,104022.24,70974.96,105834.96,69.72\r\nP087,Product 087,3390,2427,2672,54172.2,38783.46,42698.56,15.98\r\nP088,Product 088,399,504,585,68975.13,87126.48,101128.95,172.87\r\nP089,Product 089,300,374,361,10245,12772.1,12328.15,34.15\r\nP090,Product 090,621,715,801,26367.66,30358.9,34010.46,42.46\r\nP091,Product 091,686,851,526,70507.08,87465.78,54062.28,102.78\r\nP092,Product 092,920,768,804,16440.4,13724.16,14367.48,17.87\r\nP093,Product 093,454,468,470,5661.38,5835.96,5860.9,12.47\r\nP094,Product 094,1182,1009,1247,26453.16,22581.42,27907.86,22.38\r\nP095,Product 095,743,1131,1339,24236.66,36893.22,43678.18,32.62\r\nP096,Product 096,853,911,720,32780.79,35009.73,27669.6,38.43\r\nP097,Product 097,763,730,936,37028.39,35426.9,45424.08,48.53\r\nP098,Product 098,644,643,854,65900.52,65798.19,87389.82,102.33\r\nP099,Product 099,1180,1186,1101,18856.4,18952.28,17593.98,15.98\r\nP100,Product 100,695,1159,774,7999.45,13340.09,8908.74,11.51\r\nP101,Product 101,721,699,710,26129.04,25331.76,25730.4,36.24\r\nP102,Product 102,1779,1242,1683,49865.37,34813.26,47174.49,28.03\r\nP103,Product 103,1219,1581,1579,32986.14,42781.86,42727.74,27.06\r\nP104,Product 104,1850,1157,1329,18981,11870.82,13635.54,10.26\r\nP105,Product 105,340,392,394,16078.6,18537.68,18632.26,47.29\r\nP106,Product 106,556,622,477,25948.52,29028.74,22261.59,46.67\r\nP107,Product 107,365,330,342,8416.9,7609.8,7886.52,23.06\r\nP108,Product 108,746,715,681,163493.36,156699.4,149247.96,219.16\r\nP109,Product 109,742,1127,925,8703.66,13219.71,10850.25,11.73\r\nP110,Product 110,676,674,720,41526.68,41403.82,44229.6,61.43\r\nP111,Product 111,2245,2501,2252,41532.5,46268.5,41662,18.5\r\nP112,Product 112,664,574,545,9973.28,8621.48,8185.9,15.02\r\nP113,Product 113,351,450,408,4162.86,5337,4838.88,11.86\r\nP114,Product 114,1262,981,974,78092.56,60704.28,60271.12,61.88\r\nP115,Product 115,886,978,988,16027.74,17692.02,17872.92,18.09\r\nP116,Product 116,1142,1446,1109,22668.7,28703.1,22013.65,19.85\r\nP117,Product 117,779,888,1066,16421.32,18719.04,22471.28,21.08\r\nP118,Product 118,965,1169,1020,37992.05,46023.53,40157.4,39.37\r\nP119,Product 119,388,316,411,26803.04,21829.28,28391.88,69.08\r\nP120,Product 120,491,623,537,18324.12,23250.36,20040.84,37.32\r\nP121,Product 121,1297,764,1069,97223.12,57269.44,80132.24,74.96\r\nP122,Product 122,739,673,654,59785.1,54445.7,52908.6,80.9\r\nP123,Product 123,540,509,559,11529,10867.15,11934.65,21.35\r\nP124,Product 124,765,1000,1307,28871.1,37740,49326.18,37.74\r\nP125,Product 125,1210,901,1019,70022.7,52140.87,58969.53,57.87\r\nP126,Product 126,496,417,340,25831.68,21717.36,17707.2,52.08\r\nP127,Product 127,1209,1120,1921,39498.03,36590.4,62759.07,32.67\r\nP128,Product 128,1227,1119,965,119681.58,109147.26,94126.1,97.54\r\nP129,Product 129,1000,1061,1038,25310,26853.91,26271.78,25.31\r\nP130,Product 130,250,400,317,6437.5,10300,8162.75,25.75\r\nP131,Product 131,1157,1189,1043,46037.03,47310.31,41500.97,39.79\r\nP132,Product 132,1080,1216,1137,29030.4,32686.08,30562.56,26.88\r\nP133,Product 133,1821,1618,1441,26204.19,23283.02,20735.99,14.39\r\nP134,Product 134,2340,2811,2337,161857.8,194436.87,161650.29,69.17\r\nP135,Product 135,1822,1703,1577,57265.46,53525.29,49565.11,31.43\r\nP136,Product 136,699,799,959,44554.26,50928.26,61126.66,63.74\r\nP137,Product 137,525,768,600,39537.75,57838.08,45186,75.31\r\nP138,Product 138,1726,1445,1462,21540.48,18033.6,18245.76,12.48\r\nP139,Product 139,423,401,506,19995.21,18955.27,23918.62,47.27\r\nP140,Product 140,309,322,343,6723.84,7006.72,7463.68,21.76\r\nP141,Product 141,725,791,581,27571.75,30081.73,22095.43,38.03\r\nP142,Product 142,1186,1563,1343,59264.42,78103.11,67109.71,49.97\r\nP143,Product 143,735,611,678,13509.3,11230.18,12461.64,18.38\r\nP144,Product 144,1799,1957,1835,27272.84,29668.12,27818.6,15.16\r\nP145,Product 145,429,367,286,13530.66,11575.18,9020.44,31.54\r\nP146,Product 146,401,355,372,9984.9,8839.5,9262.8,24.9\r\nP147,Product 147,882,649,809,18901.26,13908.07,17336.87,21.43\r\nP148,Product 148,1131,1498,1164,45590.61,60384.38,46920.84,40.31\r\nP149,Product 149,875,688,1000,24517.5,19277.76,28020,28.02\r\nP150,Product 150,939,958,1094,42301.95,43157.9,49284.7,45.05\r\nP151,Product 151,821,875,566,41591.86,44327.5,28673.56,50.66\r\nP152,Product 152,377,372,396,7098.91,7004.76,7456.68,18.83\r\nP153,Product 153,1447,1996,1360,30705.34,42355.12,28859.2,21.22\r\nP154,Product 154,552,640,475,21754.32,25222.4,18719.75,39.41\r\nP155,Product 155,1823,1758,1883,68125.51,65696.46,70367.71,37.37\r\nP156,Product 156,557,682,721,19762.36,24197.36,25581.08,35.48\r\nP157,Product 157,1436,1912,1598,132226.88,176056.96,147143.84,92.08\r\nP158,Product 158,853,1204,810,82416.86,116330.48,78262.2,96.62\r\nP159,Product 159,592,654,885,5428.64,5997.18,8115.45,9.17\r\nP160,Product 160,937,618,874,30199.51,19918.14,28169.02,32.23\r\nP161,Product 161,324,363,279,8511.48,9536.01,7329.33,26.27\r\nP162,Product 162,932,843,784,13961.36,12628.14,11744.32,14.98\r\nP163,Product 163,2285,2450,3437,21524.7,23079,32376.54,9.42\r\nP164,Product 164,1815,1337,1356,14520,10696,10848,8\r\nP165,Product 165,410,409,498,10110.6,10085.94,12280.68,24.66\r\nP166,Product 166,1133,1211,1296,24404.82,26084.94,27915.84,21.54\r\nP167,Product 167,867,769,1221,30752.49,27276.43,43308.87,35.47\r\nP168,Product 168,1653,1230,1091,39787.71,29606.1,26260.37,24.07\r\nP169,Product 169,864,953,1064,45204.48,49860.96,55668.48,52.32\r\nP170,Product 170,820,954,900,56161.8,65339.46,61641,68.49\r\nP171,Product 171,1733,1788,1750,30570.12,31540.32,30870,17.64\r\nP172,Product 172,805,878,617,15794.1,17226.36,12105.54,19.62\r\nP173,Product 173,1912,1812,1365,149747.84,141915.84,106906.8,78.32\r\nP174,Product 174,1543,1835,1596,24101.66,28662.7,24929.52,15.62\r\nP175,Product 175,666,645,640,69696.9,67499.25,66976,104.65\r\nP176,Product 176,1089,1074,687,148648.5,146601,93775.5,136.5\r\nP177,Product 177,3246,2841,2968,74171.1,64916.85,67818.8,22.85\r\nP178,Product 178,882,758,712,28118.16,24165.04,22698.56,31.88\r\nP179,Product 179,362,562,494,14389.5,22339.5,19636.5,39.75\r\nP180,Product 180,360,329,337,4190.4,3829.56,3922.68,11.64\r\nP181,Product 181,1406,1259,1382,191005.1,171035.15,187744.7,135.85\r\nP182,Product 182,1024,942,645,8192,7536,5160,8\r\nP183,Product 183,376,406,469,10648.32,11497.92,13282.08,28.32\r\nP184,Product 184,1211,1215,871,27186.95,27276.75,19553.95,22.45\r\nP185,Product 185,892,1064,935,116646.84,139139.28,122269.95,130.77\r\nP186,Product 186,452,333,399,14147.6,10422.9,12488.7,31.3\r\nP187,Product 187,1543,969,1455,15399.14,9670.62,14520.9,9.98\r\nP188,Product 188,1753,2454,1380,76115.26,106552.68,59919.6,43.42\r\nP189,Product 189,3672,3446,2918,135533.52,127191.86,107703.38,36.91\r\nP190,Product 190,746,815,893,57427.08,62738.7,68743.14,76.98\r\nP191,Product 191,749,1060,814,5992,8480,6512,8\r\nP192,Product 192,1832,1814,1995,112301.6,111198.2,122293.5,61.3\r\nP193,Product 193,814,599,1163,53268.16,39198.56,76106.72,65.44\r\nP194,Product 194,1210,1026,1028,21598.5,18314.1,18349.8,17.85\r\nP195,Product 195,590,500,562,8590.4,7280,8182.72,14.56\r\nP196,Product 196,480,341,481,8587.2,6100.49,8605.09,17.89\r\nP197,Product 197,2081,2181,2186,135119.33,141612.33,141936.98,64.93\r\nP198,Product 198,410,439,419,21816.1,23359.19,22294.99,53.21\r\nP199,Product 199,1794,1446,1323,36346.44,29295.96,26803.98,20.26\r\nP200,Product 200,455,604,650,25552.8,33920.64,36504,56.16\r\nP201,Product 201,1002,749,1097,76071.84,56864.08,83284.24,75.92\r\nP202,Product 202,998,644,595,22914.08,14786.24,13661.2,22.96\r\nP203,Product 203,1545,1961,1972,108273.6,137426.88,138197.76,70.08\r\nP204,Product 204,789,1039,1228,16797.81,22120.31,26144.12,21.29\r\nP205,Product 205,3379,1941,4370,74473.16,42779.64,96314.8,22.04\r\nP206,Product 206,534,408,450,13900.02,10620.24,11713.5,26.03\r\nP207,Product 207,1122,915,762,40246.14,32821.05,27332.94,35.87\r\nP208,Product 208,691,727,695,5528,5816,5560,8\r\nP209,Product 209,965,884,984,12506.4,11456.64,12752.64,12.96\r\nP210,Product 210,1963,3059,2870,15704,24472,22960,8\r\nP211,Product 211,800,1293,1157,36776,59439.21,53187.29,45.97\r\nP212,Product 212,497,395,408,36609.02,29095.7,30053.28,73.66\r\nP213,Product 213,1038,1134,1237,88437.6,96616.8,105392.4,85.2\r\nP214,Product 214,730,1151,841,5840,9208,6728,8\r\nP215,Product 215,547,391,627,16218.55,11593.15,18590.55,29.65\r\nP216,Product 216,1011,1212,1443,11848.92,14204.64,16911.96,11.72\r\nP217,Product 217,583,634,651,6028.22,6555.56,6731.34,10.34\r\nP218,Product 218,685,615,712,12699.9,11402.1,13200.48,18.54\r\nP219,Product 219,811,993,672,8710.14,10664.82,7217.28,10.74\r\nP220,Product 220,1147,1051,1257,151541.64,138858.12,166074.84,132.12\r\nP221,Product 221,811,1174,1357,7599.07,11000.38,12715.09,9.37\r\nP222,Product 222,803,710,934,10848.53,9592.1,12618.34,13.51\r\nP223,Product 223,597,754,581,14853.36,18759.52,14455.28,24.88\r\nP224,Product 224,447,373,438,13182.03,10999.77,12916.62,29.49\r\nP225,Product 225,584,726,652,16860.08,20959.62,18823.24,28.87\r\nP226,Product 226,557,523,484,6450.06,6056.34,5604.72,11.58\r\nP227,Product 227,952,744,807,32263.28,25214.16,27349.23,33.89\r\nP228,Product 228,2703,2013,2505,93821.13,69871.23,86948.55,34.71\r\nP229,Product 229,502,447,497,24111.06,21469.41,23870.91,48.03\r\nP230,Product 230,691,602,664,17095.34,14893.48,16427.36,24.74\r\nP231,Product 231,353,313,256,20382.22,18072.62,14781.44,57.74\r\nP232,Product 232,1024,1124,779,9850.88,10812.88,7493.98,9.62\r\nP233,Product 233,334,339,305,25190.28,25567.38,23003.1,75.42\r\nP234,Product 234,441,506,601,23628.78,27111.48,32201.58,53.58\r\nP235,Product 235,1643,1578,1349,59295.87,56950.02,48685.41,36.09\r\nP236,Product 236,406,400,382,16292.78,16052,15329.66,40.13\r\nP237,Product 237,622,881,1145,36579.82,51811.61,67337.45,58.81\r\nP238,Product 238,1265,1129,1703,67804,60514.4,91280.8,53.6\r\nP239,Product 239,2270,2384,2045,29373.8,30848.96,26462.3,12.94\r\nP240,Product 240,386,496,554,25109.3,32264.8,36037.7,65.05\r\nP241,Product 241,497,618,648,16619.68,20665.92,21669.12,33.44\r\nP242,Product 242,2556,4018,3032,173475.72,272701.66,205781.84,67.87\r\nP243,Product 243,841,737,816,32218.71,28234.47,31260.96,38.31\r\nP244,Product 244,468,484,454,6346.08,6563.04,6156.24,13.56\r\nP245,Product 245,435,512,495,5433.15,6394.88,6182.55,12.49\r\nP246,Product 246,739,669,698,28946.63,26204.73,27340.66,39.17\r\nP247,Product 247,759,668,709,48773.34,42925.68,45560.34,64.26\r\nP248,Product 248,1646,1076,2115,15274.88,9985.28,19627.2,9.28\r\nP249,Product 249,1287,1391,1550,28223.91,30504.63,33991.5,21.93\r\nP250,Product 250,502,400,436,31500.5,25100,27359,62.75\r\n'}

In [ ]:
import pandas as pd

In [ ]:
financial_plan = pd.read_csv('financial_plan.csv')

Data Clean

In [ ]:
financial_plan.head()

,ProductID,Product_name,Plan_2023_units,Plan_2024_units,Plan_2025_units,Plan_2023_PLN,Plan_2024_PLN,Plan_2025_PLN,Price_PLN_per_unit
0,P001,Product 001,486,695,543,10021.32,14330.90,11196.66,20.62
1,P002,Product 002,347,376,360,3480.41,3771.28,3610.80,10.03
2,P003,Product 003,599,849,818,21569.99,30572.49,29456.18,36.01
3,P004,Product 004,1024,1920,1693,28897.28,54182.40,47776.46,28.22
4,P005,Product 005,333,406,321,28151.82,34323.24,27137.34,84.54

In [ ]:
financial_plan.dtypes

ProductID              object
Product_name           object
Plan_2023_units         int64
Plan_2024_units         int64
Plan_2025_units         int64
Plan_2023_PLN         float64
Plan_2024_PLN         float64
Plan_2025_PLN         float64
Price_PLN_per_unit    float64
dtype: object

In [ ]:
financial_plan.isnull().sum()

ProductID             0
Product_name          0
Plan_2023_units       0
Plan_2024_units       0
Plan_2025_units       0
Plan_2023_PLN         0
Plan_2024_PLN         0
Plan_2025_PLN         0
Price_PLN_per_unit    0
dtype: int64

In [ ]:
financial_plan = financial_plan.drop(columns=['Product_name', 'Price_PLN_per_unit'])

In [ ]:
financial_plan.head()

,ProductID,Plan_2023_units,Plan_2024_units,Plan_2025_units,Plan_2023_PLN,Plan_2024_PLN,Plan_2025_PLN
0,P001,486,695,543,10021.32,14330.90,11196.66
1,P002,347,376,360,3480.41,3771.28,3610.80
2,P003,599,849,818,21569.99,30572.49,29456.18
3,P004,1024,1920,1693,28897.28,54182.40,47776.46
4,P005,333,406,321,28151.82,34323.24,27137.34

melt and Pivot (23/24) e 2025

In [ ]:
# Select specific columns
selected_columns_2324 = financial_plan[
    ['ProductID',
     'Plan_2023_units',
     'Plan_2024_units',
     'Plan_2023_PLN',
     'Plan_2024_PLN'
     ]]
display(selected_columns_2324.head())

  ProductID  Plan_2023_units  Plan_2024_units  Plan_2023_PLN  Plan_2024_PLN
0      P001              486              695       10021.32       14330.90
1      P002              347              376        3480.41        3771.28
2      P003              599              849       21569.99       30572.49
3      P004             1024             1920       28897.28       54182.40
4      P005              333              406       28151.82       34323.24

In [ ]:
# Select specific columns
selected_columns_2025 = financial_plan[
    ['ProductID',
    'Plan_2025_units',
     'Plan_2025_PLN'
     ]]
display(selected_columns_2025.head())

  ProductID  Plan_2025_units  Plan_2025_PLN
0      P001              543       11196.66
1      P002              360        3610.80
2      P003              818       29456.18
3      P004             1693       47776.46
4      P005              321       27137.34

In [ ]:
# Melt the 2023 and 2024 data
melted_2324 = selected_columns_2324.melt(
    id_vars=['ProductID'],
    value_vars=['Plan_2023_units', 'Plan_2024_units', 'Plan_2023_PLN', 'Plan_2024_PLN'],
    var_name='Variable',
    value_name='Value'
)
display(melted_2324.head())

  ProductID         Variable   Value
0      P001  Plan_2023_units   486.0
1      P002  Plan_2023_units   347.0
2      P003  Plan_2023_units   599.0
3      P004  Plan_2023_units  1024.0
4      P005  Plan_2023_units   333.0

In [ ]:
# Melt the 2025 data
melted_2025 = selected_columns_2025.melt(
    id_vars=['ProductID'],
    value_vars=['Plan_2025_units', 'Plan_2025_PLN'],
    var_name='Variable',
    value_name='Value'
)
display(melted_2025.head())

  ProductID         Variable   Value
0      P001  Plan_2025_units   543.0
1      P002  Plan_2025_units   360.0
2      P003  Plan_2025_units   818.0
3      P004  Plan_2025_units  1693.0
4      P005  Plan_2025_units   321.0

In [ ]:


melted_2324[['Prefix', 'Year', 'Measure']] = melted_2324['Variable'].str.split('_', expand=True)


display(melted_2324.head())

  ProductID         Variable   Value Prefix  Year Measure
0      P001  Plan_2023_units   486.0   Plan  2023   units
1      P002  Plan_2023_units   347.0   Plan  2023   units
2      P003  Plan_2023_units   599.0   Plan  2023   units
3      P004  Plan_2023_units  1024.0   Plan  2023   units
4      P005  Plan_2023_units   333.0   Plan  2023   units

In [ ]:
melted_2324['Year'] = melted_2324['Year'].astype(int)
melted_2324 = melted_2324.drop(columns=['Variable', 'Prefix'])
display(melted_2324.head())

  ProductID   Value  Year Measure
0      P001   486.0  2023   units
1      P002   347.0  2023   units
2      P003   599.0  2023   units
3      P004  1024.0  2023   units
4      P005   333.0  2023   units

In [ ]:
melted_2025[['Prefix', 'Year', 'Measure']] = melted_2025['Variable'].str.split('_', expand=True)
melted_2025['Year'] = melted_2025['Year'].astype(int)
melted_2025 = melted_2025.drop(columns=['Variable', 'Prefix'])
display(melted_2025.head())

  ProductID   Value  Year Measure
0      P001   543.0  2025   units
1      P002   360.0  2025   units
2      P003   818.0  2025   units
3      P004  1693.0  2025   units
4      P005   321.0  2025   units

In [ ]:
melted_2324.dtypes
melted_2025.dtypes

ProductID     object
Value        float64
Year           int64
Measure       object
dtype: object

In [ ]:
financial_plan_2324_final = melted_2324.pivot(
    index=['ProductID', 'Year'], columns='Measure', values='Value')

In [ ]:
melted_2324.head()

  ProductID   Value  Year Measure
0      P001   486.0  2023   units
1      P002   347.0  2023   units
2      P003   599.0  2023   units
3      P004  1024.0  2023   units
4      P005   333.0  2023   units

In [ ]:
financial_plan_2324_final.head()

Measure              PLN  units
ProductID Year
P001      2023  10021.32  486.0
          2024  14330.90  695.0
P002      2023   3480.41  347.0
          2024   3771.28  376.0
P003      2023  21569.99  599.0

In [ ]:
financial_plan_2324_final = financial_plan_2324_final.reset_index()
display(financial_plan_2324_final.head())
financial_plan_2324_final.dtypes

Measure ProductID  Year       PLN  units
0            P001  2023  10021.32  486.0
1            P001  2024  14330.90  695.0
2            P002  2023   3480.41  347.0
3            P002  2024   3771.28  376.0
4            P003  2023  21569.99  599.0

Measure
ProductID     object
Year           int64
PLN          float64
units        float64
dtype: object

In [ ]:
financial_plan_2025_final = melted_2025.pivot(
    index=['ProductID', 'Year'], columns='Measure', values='Value')
display(financial_plan_2025_final.head())

Measure              PLN   units
ProductID Year
P001      2025  11196.66   543.0
P002      2025   3610.80   360.0
P003      2025  29456.18   818.0
P004      2025  47776.46  1693.0
P005      2025  27137.34   321.0

In [ ]:
financial_plan_2025_final = financial_plan_2025_final.reset_index()
display(financial_plan_2025_final.head())
financial_plan_2025_final.dtypes

Measure ProductID  Year       PLN   units
0            P001  2025  11196.66   543.0
1            P002  2025   3610.80   360.0
2            P003  2025  29456.18   818.0
3            P004  2025  47776.46  1693.0
4            P005  2025  27137.34   321.0

Measure
ProductID     object
Year           int64
PLN          float64
units        float64
dtype: object

In [ ]:
financial_plan_2025_final = financial_plan_2025_final.reset_index()
display(financial_plan_2025_final.head())
financial_plan_2025_final.dtypes

Measure  index ProductID  Year       PLN   units
0            0      P001  2025  11196.66   543.0
1            1      P002  2025   3610.80   360.0
2            2      P003  2025  29456.18   818.0
3            3      P004  2025  47776.46  1693.0
4            4      P005  2025  27137.34   321.0

Measure
index          int64
ProductID     object
Year           int64
PLN          float64
units        float64
dtype: object

In [ ]:
financial_plan_2324_final.isnull().sum()
financial_plan_2025_final.isnull().sum()

Measure
index        0
ProductID    0
Year         0
PLN          0
units        0
dtype: int64

In [ ]:
financial_plan_2324_final.shape

(500, 4)

In [ ]:
financial_plan_2025_final.shape

(250, 5)

In [ ]:
financial_plan_2324_final['units'] = financial_plan_2324_final['units'].astype(int)
financial_plan_2025_final['units'] = financial_plan_2025_final['units'].astype(int)

In [ ]:
financial_plan_2324_final.to_csv('financial_plan_2324_final.csv', index=False)
financial_plan_2025_final_cleaned = financial_plan_2025_final.drop(columns=['index'])
financial_plan_2025_final_cleaned.to_csv('financial_plan_2025_final.csv', index=False)
print('Files saved successfully!')

Files saved successfully!

In [ ]:
import subprocess

# Display the header and first few lines of the CSV file
result = subprocess.run(['head', '-n', '5', 'financial_plan_2025_final.csv'], capture_output=True, text=True)
print(result.stdout)

ProductID,Year,PLN,units
P001,2025,11196.66,543
P002,2025,3610.8,360
P003,2025,29456.18,818
P004,2025,47776.46,1693

In [ ]:
from google.colab import files

files.download('financial_plan_2324_final.csv')
files.download('financial_plan_2025_final.csv')