In [ ]:
from google.colab import files
files.upload()

Saving products_parameters.csv to products_parameters.csv

{'products_parameters.csv': b'ProductID,Product_name,Storage_cost_PLN_per_unit_month,Shelf_life_months,Lead_time_months,Safety_stock_months,Price_PLN_per_unit\r\nP001,Product 001,0.34,20,3,0.7,20.62\r\nP002,Product 002,0.2,22,2,1.2,10.03\r\nP003,Product 003,0.95,15,1,1.1,36.01\r\nP004,Product 004,0.67,12,3,1.4,28.22\r\nP005,Product 005,1.47,12,2,1.8,84.54\r\nP006,Product 006,0.89,14,3,0.9,35.65\r\nP007,Product 007,0.71,14,3,0.6,15.3\r\nP008,Product 008,0.46,18,1,1.3,8.61\r\nP009,Product 009,1.02,12,1,1.5,45.15\r\nP010,Product 010,0.93,24,2,1.4,22.46\r\nP011,Product 011,0.81,22,1,1.5,26.96\r\nP012,Product 012,0.89,12,2,0.6,18.06\r\nP013,Product 013,0.5,9,1,1.2,8\r\nP014,Product 014,1.21,21,2,0.9,56.33\r\nP015,Product 015,0.48,10,3,1.4,40.95\r\nP016,Product 016,1.11,10,1,1.9,33.66\r\nP017,Product 017,0.7,17,2,1,46.9\r\nP018,Product 018,0.22,23,3,0.9,11.2\r\nP019,Product 019,1.3,22,1,0.6,124.79\r\nP020,Product 020,0.77,21,3,0.9,22.44\r\nP021,Product 021,0.95,21,3,1.8,37.33\r\nP022,Product 022,1.26,14,1,1.7,49.88\r\nP023,Product 023,0.57,11,3,0.7,8\r\nP024,Product 024,1.33,9,2,1.2,100.14\r\nP025,Product 025,0.59,19,1,1.6,29.73\r\nP026,Product 026,0.24,11,3,1.6,8\r\nP027,Product 027,0.93,11,3,1.9,21.74\r\nP028,Product 028,2.52,24,3,1.4,220.81\r\nP029,Product 029,0.33,14,1,1.3,23.83\r\nP030,Product 030,0.28,22,3,1.3,9.8\r\nP031,Product 031,0.63,21,1,1.3,25.19\r\nP032,Product 032,0.74,21,1,1.8,38.05\r\nP033,Product 033,0.63,16,3,1,17.9\r\nP034,Product 034,0.65,12,1,0.9,18.13\r\nP035,Product 035,1.09,24,2,0.6,69.12\r\nP036,Product 036,1.12,16,1,1,53.26\r\nP037,Product 037,0.68,14,1,1.7,28.38\r\nP038,Product 038,0.94,13,3,0.7,27.06\r\nP039,Product 039,0.58,14,1,1.8,31.81\r\nP040,Product 040,0.6,14,2,1.1,20.59\r\nP041,Product 041,0.35,12,2,1.9,28.29\r\nP042,Product 042,0.67,9,2,1.6,31.58\r\nP043,Product 043,1.25,9,3,1.5,86.28\r\nP044,Product 044,0.46,22,3,1.1,11.88\r\nP045,Product 045,0.74,10,1,1.6,57.69\r\nP046,Product 046,1.36,10,2,0.6,99.94\r\nP047,Product 047,0.46,18,1,1.7,14.99\r\nP048,Product 048,1.05,24,1,2,32.77\r\nP049,Product 049,1.01,12,2,1.2,34.43\r\nP050,Product 050,0.74,23,1,1.4,25.24\r\nP051,Product 051,0.4,12,1,1.7,19.91\r\nP052,Product 052,0.63,11,2,0.9,13.47\r\nP053,Product 053,0.2,15,1,1.5,8\r\nP054,Product 054,1.17,14,1,1.7,43.84\r\nP055,Product 055,0.32,16,2,0.9,8\r\nP056,Product 056,1.09,12,3,1.5,41.77\r\nP057,Product 057,0.97,19,3,1.7,56.61\r\nP058,Product 058,0.37,18,2,0.8,13.14\r\nP059,Product 059,0.8,9,3,1.8,43.47\r\nP060,Product 060,1.29,21,3,1.7,48.73\r\nP061,Product 061,1.14,24,3,0.8,48.77\r\nP062,Product 062,0.88,23,3,1.2,20.42\r\nP063,Product 063,0.8,24,3,1.7,37.07\r\nP064,Product 064,0.56,17,1,1.2,33.18\r\nP065,Product 065,0.45,23,2,1.7,15.55\r\nP066,Product 066,0.84,11,2,1,19.2\r\nP067,Product 067,1.23,13,1,1.8,46.38\r\nP068,Product 068,0.76,19,2,1,19.01\r\nP069,Product 069,1.09,14,2,1.1,39.96\r\nP070,Product 070,0.78,24,3,1.6,30.6\r\nP071,Product 071,0.42,17,3,1,23.91\r\nP072,Product 072,0.77,13,3,1.3,31.06\r\nP073,Product 073,0.87,10,3,0.7,36.81\r\nP074,Product 074,0.45,14,1,0.7,30.09\r\nP075,Product 075,0.75,10,3,1.7,32.7\r\nP076,Product 076,0.76,17,1,2,47.9\r\nP077,Product 077,0.98,11,2,1.2,25.21\r\nP078,Product 078,1.08,13,3,0.7,33.5\r\nP079,Product 079,1.01,22,3,1.3,24.74\r\nP080,Product 080,0.89,12,1,1.9,38.93\r\nP081,Product 081,0.9,14,3,1.9,26.21\r\nP082,Product 082,1.24,11,3,1.5,49.01\r\nP083,Product 083,1.19,11,3,1.9,65.91\r\nP084,Product 084,0.2,13,1,1.4,10.08\r\nP085,Product 085,1.03,15,1,0.5,81.85\r\nP086,Product 086,0.93,15,3,1.9,69.72\r\nP087,Product 087,0.45,13,2,0.8,15.98\r\nP088,Product 088,2.39,19,3,0.5,172.87\r\nP089,Product 089,1.01,14,1,1.1,34.15\r\nP090,Product 090,0.93,22,2,1.8,42.46\r\nP091,Product 091,1.09,19,1,1,102.78\r\nP092,Product 092,0.83,9,2,1,17.87\r\nP093,Product 093,0.62,20,3,1,12.47\r\nP094,Product 094,0.73,20,3,1.2,22.38\r\nP095,Product 095,0.41,17,3,1.6,32.62\r\nP096,Product 096,1.13,15,2,1.4,38.43\r\nP097,Product 097,1.27,22,3,0.8,48.53\r\nP098,Product 098,1.13,23,2,1,102.33\r\nP099,Product 099,0.4,19,3,1.2,15.98\r\nP100,Product 100,0.47,23,3,1.6,11.51\r\nP101,Product 101,1.02,24,2,1.9,36.24\r\nP102,Product 102,1.04,13,1,1.4,28.03\r\nP103,Product 103,0.4,12,2,1,27.06\r\nP104,Product 104,0.35,20,1,2,10.26\r\nP105,Product 105,0.53,10,2,0.7,47.29\r\nP106,Product 106,0.83,19,1,1.8,46.67\r\nP107,Product 107,0.49,10,3,1.1,23.06\r\nP108,Product 108,2.61,21,3,1.9,219.16\r\nP109,Product 109,0.68,10,3,0.8,11.73\r\nP110,Product 110,1.07,14,2,1.1,61.43\r\nP111,Product 111,0.24,23,2,0.6,18.5\r\nP112,Product 112,0.22,20,2,1.9,15.02\r\nP113,Product 113,0.59,16,2,0.7,11.86\r\nP114,Product 114,1.18,11,1,1.4,61.88\r\nP115,Product 115,0.41,21,2,0.8,18.09\r\nP116,Product 116,0.82,13,3,1.9,19.85\r\nP117,Product 117,0.73,11,2,1.5,21.08\r\nP118,Product 118,0.8,22,1,1.2,39.37\r\nP119,Product 119,1.34,22,1,0.5,69.08\r\nP120,Product 120,0.86,22,2,0.7,37.32\r\nP121,Product 121,1.51,13,3,1.5,74.96\r\nP122,Product 122,1.31,20,3,1.2,80.9\r\nP123,Product 123,0.44,11,2,1.6,21.35\r\nP124,Product 124,0.48,23,2,1.5,37.74\r\nP125,Product 125,0.7,14,3,0.6,57.87\r\nP126,Product 126,1.32,17,3,0.5,52.08\r\nP127,Product 127,1.03,9,3,0.9,32.67\r\nP128,Product 128,1.76,17,1,1.4,97.54\r\nP129,Product 129,0.32,22,1,0.8,25.31\r\nP130,Product 130,0.8,18,1,1.2,25.75\r\nP131,Product 131,1,10,2,1.6,39.79\r\nP132,Product 132,0.91,21,3,1.1,26.88\r\nP133,Product 133,0.51,12,3,0.7,14.39\r\nP134,Product 134,0.84,12,1,1.2,69.17\r\nP135,Product 135,0.74,9,1,1.5,31.43\r\nP136,Product 136,1.17,9,2,2,63.74\r\nP137,Product 137,1.52,11,3,1.9,75.31\r\nP138,Product 138,0.75,16,1,1.7,12.48\r\nP139,Product 139,0.88,12,3,1.7,47.27\r\nP140,Product 140,0.89,10,3,1.5,21.76\r\nP141,Product 141,0.91,9,1,1,38.03\r\nP142,Product 142,0.56,17,2,0.9,49.97\r\nP143,Product 143,0.48,16,2,1.4,18.38\r\nP144,Product 144,0.39,11,3,1.1,15.16\r\nP145,Product 145,0.67,23,2,1.2,31.54\r\nP146,Product 146,0.61,15,2,1.4,24.9\r\nP147,Product 147,0.34,18,3,0.6,21.43\r\nP148,Product 148,0.7,10,2,0.9,40.31\r\nP149,Product 149,0.61,9,3,0.7,28.02\r\nP150,Product 150,0.7,23,3,0.8,45.05\r\nP151,Product 151,1.15,17,2,1.9,50.66\r\nP152,Product 152,0.37,22,3,1.5,18.83\r\nP153,Product 153,0.73,12,3,1.1,21.22\r\nP154,Product 154,1.15,17,3,1.8,39.41\r\nP155,Product 155,0.82,15,1,0.8,37.37\r\nP156,Product 156,1.06,11,1,1.5,35.48\r\nP157,Product 157,1.66,24,2,1.7,92.08\r\nP158,Product 158,1.08,19,3,1.1,96.62\r\nP159,Product 159,0.24,16,3,1,9.17\r\nP160,Product 160,0.82,16,1,1,32.23\r\nP161,Product 161,0.66,20,1,1.1,26.27\r\nP162,Product 162,0.24,20,2,0.7,14.98\r\nP163,Product 163,0.2,15,3,1.2,9.42\r\nP164,Product 164,0.29,12,1,1.9,8\r\nP165,Product 165,0.83,15,1,1.4,24.66\r\nP166,Product 166,0.61,15,2,1.5,21.54\r\nP167,Product 167,1.01,18,2,1,35.47\r\nP168,Product 168,0.86,20,3,2,24.07\r\nP169,Product 169,1.29,10,2,1.7,52.32\r\nP170,Product 170,1,24,1,1.3,68.49\r\nP171,Product 171,0.53,14,2,1.1,17.64\r\nP172,Product 172,0.79,12,1,1.2,19.62\r\nP173,Product 173,1.1,15,3,1.2,78.32\r\nP174,Product 174,0.68,18,1,1.9,15.62\r\nP175,Product 175,1.81,20,1,2,104.65\r\nP176,Product 176,1.46,11,3,1.7,136.5\r\nP177,Product 177,0.53,22,1,1.8,22.85\r\nP178,Product 178,1.11,20,1,1.9,31.88\r\nP179,Product 179,1.05,24,2,1.8,39.75\r\nP180,Product 180,0.67,14,2,0.5,11.64\r\nP181,Product 181,1.94,21,1,1.4,135.85\r\nP182,Product 182,0.67,18,3,1.4,8\r\nP183,Product 183,1.02,14,3,0.6,28.32\r\nP184,Product 184,0.29,16,1,1.5,22.45\r\nP185,Product 185,1.68,22,1,1.3,130.77\r\nP186,Product 186,0.52,16,1,1.5,31.3\r\nP187,Product 187,0.6,23,2,1.2,9.98\r\nP188,Product 188,0.98,21,1,1.5,43.42\r\nP189,Product 189,1.09,9,1,1.6,36.91\r\nP190,Product 190,1.43,23,3,1,76.98\r\nP191,Product 191,0.27,10,2,1.6,8\r\nP192,Product 192,0.84,17,3,0.6,61.3\r\nP193,Product 193,1.01,24,3,1.3,65.44\r\nP194,Product 194,0.95,14,1,1.6,17.85\r\nP195,Product 195,0.25,22,1,1.6,14.56\r\nP196,Product 196,0.53,19,3,0.6,17.89\r\nP197,Product 197,1.36,13,2,1,64.93\r\nP198,Product 198,1.06,10,2,0.6,53.21\r\nP199,Product 199,0.96,11,2,1.9,20.26\r\nP200,Product 200,1,23,2,1.6,56.16\r\nP201,Product 201,1.51,16,3,1.6,75.92\r\nP202,Product 202,0.43,14,1,2,22.96\r\nP203,Product 203,0.78,14,2,1.9,70.08\r\nP204,Product 204,0.83,19,3,1.8,21.29\r\nP205,Product 205,0.71,20,1,1,22.04\r\nP206,Product 206,0.69,13,3,1.2,26.03\r\nP207,Product 207,0.97,22,3,0.6,35.87\r\nP208,Product 208,0.59,21,3,1.6,8\r\nP209,Product 209,0.49,21,1,1.3,12.96\r\nP210,Product 210,0.34,12,2,1.3,8\r\nP211,Product 211,0.57,16,2,2,45.97\r\nP212,Product 212,1.1,17,1,1.3,73.66\r\nP213,Product 213,1.26,17,1,2,85.2\r\nP214,Product 214,0.39,21,3,0.7,8\r\nP215,Product 215,0.77,16,3,1.8,29.65\r\nP216,Product 216,0.72,24,2,0.6,11.72\r\nP217,Product 217,0.76,12,3,1.8,10.34\r\nP218,Product 218,0.74,20,3,1.4,18.54\r\nP219,Product 219,0.79,23,1,0.6,10.74\r\nP220,Product 220,1.7,23,3,0.7,132.12\r\nP221,Product 221,0.85,11,3,1.2,9.37\r\nP222,Product 222,0.61,24,1,1.6,13.51\r\nP223,Product 223,0.46,12,3,1.2,24.88\r\nP224,Product 224,1.09,16,2,1.8,29.49\r\nP225,Product 225,0.74,22,1,1.6,28.87\r\nP226,Product 226,0.25,19,2,1,11.58\r\nP227,Product 227,0.49,24,3,2,33.89\r\nP228,Product 228,0.93,16,1,1.3,34.71\r\nP229,Product 229,0.78,23,3,1.3,48.03\r\nP230,Product 230,0.59,10,2,1.5,24.74\r\nP231,Product 231,1.18,15,2,1.4,57.74\r\nP232,Product 232,0.83,19,1,1,9.62\r\nP233,Product 233,1.33,10,1,1,75.42\r\nP234,Product 234,1.2,13,1,0.9,53.58\r\nP235,Product 235,1.14,20,3,1,36.09\r\nP236,Product 236,0.62,16,2,1.7,40.13\r\nP237,Product 237,1.04,17,2,0.6,58.81\r\nP238,Product 238,1.1,20,3,1.4,53.6\r\nP239,Product 239,0.22,18,2,1.2,12.94\r\nP240,Product 240,1.42,12,1,1.7,65.05\r\nP241,Product 241,0.88,23,2,0.9,33.44\r\nP242,Product 242,1.38,19,2,1.6,67.87\r\nP243,Product 243,0.47,20,1,1.8,38.31\r\nP244,Product 244,0.68,22,2,2,13.56\r\nP245,Product 245,0.59,12,1,1.4,12.49\r\nP246,Product 246,1.15,20,2,1.5,39.17\r\nP247,Product 247,1.12,13,2,0.5,64.26\r\nP248,Product 248,0.24,23,3,0.8,9.28\r\nP249,Product 249,0.7,22,1,1.3,21.93\r\nP250,Product 250,0.78,19,1,1.9,62.75\r\n'}

In [ ]:
import pandas as pd

In [ ]:
product_parameter = pd.read_csv('products_parameters.csv')

In [ ]:
product_parameter.head()

,ProductID,Product_name,Storage_cost_PLN_per_unit_month,Shelf_life_months,Lead_time_months,Safety_stock_months,Price_PLN_per_unit
0,P001,Product 001,0.34,20,3,0.7,20.62
1,P002,Product 002,0.20,22,2,1.2,10.03
2,P003,Product 003,0.95,15,1,1.1,36.01
3,P004,Product 004,0.67,12,3,1.4,28.22
4,P005,Product 005,1.47,12,2,1.8,84.54

In [ ]:
product_parameter.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 7 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   ProductID                        250 non-null    object
 1   Product_name                     250 non-null    object
 2   Storage_cost_PLN_per_unit_month  250 non-null    float64
 3   Shelf_life_months                250 non-null    int64
 4   Lead_time_months                 250 non-null    int64
 5   Safety_stock_months              250 non-null    float64
 6   Price_PLN_per_unit               250 non-null    float64
dtypes: float64(3), int64(2), object(2)
memory usage: 13.8+ KB

In [ ]:
# duplicati?

product_parameter.duplicated().sum()

np.int64(0)

In [ ]:
#range max e min


product_parameter["Price_PLN_per_unit"].describe()

count    250.000000
mean      39.285960
std       31.833642
min        8.000000
25%       18.612500
50%       31.485000
75%       48.760000
max      220.810000
Name: Price_PLN_per_unit, dtype: float64