In [ ]:
from google.colab import files
files.upload()

Saving sales_test_2025.csv to sales_test_2025.csv

{'sales_test_2025.csv': b'ProductID,Product_name,Type,2025-01,2025-02,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12\r\nP001,Product 001,Sales,54,59,51,46,45,52,77,67,62,55,43,39\r\nP001,Product 001,Inventory_level,202,143,92,46,1,237,160,93,31,392,349,310\r\nP002,Product 002,Sales,30,30,31,37,41,40,30,35,38,37,43,32\r\nP002,Product 002,Inventory_level,230,200,169,132,91,51,21,284,246,209,166,134\r\nP003,Product 003,Sales,68,74,58,51,64,73,69,78,71,68,82,80\r\nP003,Product 003,Inventory_level,350,276,218,167,103,30,277,199,128,60,344,264\r\nP004,Product 004,Sales,114,137,146,105,124,116,161,117,136,142,173,140\r\nP004,Product 004,Inventory_level,568,431,285,180,56,692,531,414,278,136,755,615\r\nP005,Product 005,Sales,29,31,34,32,31,29,38,30,28,27,30,26\r\nP005,Product 005,Inventory_level,152,121,87,55,24,159,121,91,63,36,150,124\r\nP006,Product 006,Sales,69,14,59,65,41,65,43,40,35,69,46,61\r\nP006,Product 006,Inventory_level,141,127,68,3,148,83,40,0,225,156,110,49\r\nP007,Product 007,Sales,82,71,73,78,70,66,69,70,63,95,88,84\r\nP007,Product 007,Inventory_level,448,377,304,226,156,90,21,503,440,345,257,173\r\nP008,Product 008,Sales,94,62,95,80,126,360,123,171,104,136,44,83\r\nP008,Product 008,Inventory_level,1079,1017,922,842,716,356,233,62,1487,1351,1307,1224\r\nP009,Product 009,Sales,94,97,85,65,105,98,112,130,88,92,86,67\r\nP009,Product 009,Inventory_level,823,726,641,576,471,373,261,131,43,836,750,683\r\nP010,Product 010,Sales,84,75,98,92,72,64,72,84,72,85,72,83\r\nP010,Product 010,Inventory_level,211,136,38,292,220,156,84,0,234,149,77,302\r\nP011,Product 011,Sales,56,65,66,53,52,61,59,58,25,48,50,63\r\nP011,Product 011,Inventory_level,177,112,46,435,383,322,263,205,180,132,82,19\r\nP012,Product 012,Sales,93,93,63,76,112,100,106,95,79,79,76,97\r\nP012,Product 012,Inventory_level,248,155,92,601,489,389,283,188,109,688,612,515\r\nP013,Product 013,Sales,410,105,199,200,81,138,87,529,138,166,145,170\r\nP013,Product 013,Inventory_level,504,399,200,0,900,762,675,146,8,1102,957,787\r\nP014,Product 014,Sales,33,32,22,29,24,37,31,37,26,31,32,29\r\nP014,Product 014,Inventory_level,58,26,238,209,185,148,117,80,54,23,213,184\r\nP015,Product 015,Sales,104,111,125,74,118,94,119,130,126,113,125,95\r\nP015,Product 015,Inventory_level,704,593,468,394,276,182,63,820,694,581,456,361\r\nP016,Product 016,Sales,65,56,81,76,56,64,92,85,61,75,70,57\r\nP016,Product 016,Inventory_level,333,277,196,120,64,0,400,315,254,179,109,52\r\nP017,Product 017,Sales,58,61,56,43,40,56,45,59,51,61,70,49\r\nP017,Product 017,Inventory_level,140,79,23,216,176,120,75,16,180,119,49,0\r\nP018,Product 018,Sales,35,32,36,21,30,42,19,36,34,38,31,38\r\nP018,Product 018,Inventory_level,145,113,77,56,26,131,112,76,42,4,154,116\r\nP019,Product 019,Sales,20,34,36,39,48,37,55,45,40,36,34,32\r\nP019,Product 019,Inventory_level,166,132,96,57,9,222,167,122,82,46,12,202\r\nP020,Product 020,Sales,168,182,152,186,185,296,343,303,171,175,140,186\r\nP020,Product 020,Inventory_level,217,1267,1115,929,744,448,105,1727,1556,1381,1241,1055\r\nP021,Product 021,Sales,48,41,46,51,52,48,50,54,47,46,38,50\r\nP021,Product 021,Inventory_level,216,175,129,78,26,228,178,124,77,31,241,191\r\nP022,Product 022,Sales,46,37,33,29,34,40,59,48,40,39,40,47\r\nP022,Product 022,Inventory_level,19,195,162,133,99,59,0,186,146,107,67,20\r\nP023,Product 023,Sales,63,61,46,50,55,79,71,80,57,40,57,41\r\nP023,Product 023,Inventory_level,134,73,27,205,150,71,0,222,165,125,68,27\r\nP024,Product 024,Sales,50,39,53,44,64,84,60,53,55,40,54,49\r\nP024,Product 024,Inventory_level,134,95,42,190,126,42,241,188,133,93,39,190\r\nP025,Product 025,Sales,64,72,58,71,87,103,72,108,62,68,70,41\r\nP025,Product 025,Inventory_level,72,0,311,240,153,50,414,306,244,176,106,65\r\nP026,Product 026,Sales,109,129,177,201,164,132,149,157,122,165,197,130\r\nP026,Product 026,Inventory_level,827,698,521,320,156,931,782,625,503,338,141,820\r\nP027,Product 027,Sales,63,61,41,59,67,58,41,47,57,52,64,60\r\nP027,Product 027,Inventory_level,151,90,49,378,311,253,212,165,108,56,359,299\r\nP028,Product 028,Sales,59,85,83,71,69,56,80,66,75,54,75,67\r\nP028,Product 028,Inventory_level,240,155,72,534,465,409,329,263,188,134,59,473\r\nP029,Product 029,Sales,40,25,44,31,32,43,30,53,41,40,49,41\r\nP029,Product 029,Inventory_level,231,206,162,131,99,56,26,259,218,178,129,88\r\nP030,Product 030,Sales,113,159,184,149,116,184,235,208,165,162,151,140\r\nP030,Product 030,Inventory_level,577,418,234,85,792,608,373,165,0,869,718,578\r\nP031,Product 031,Sales,97,264,79,70,93,64,215,67,82,97,34,52\r\nP031,Product 031,Inventory_level,1031,767,688,618,525,461,246,179,97,0,979,927\r\nP032,Product 032,Sales,47,34,34,33,27,33,43,40,44,33,33,28\r\nP032,Product 032,Inventory_level,92,58,24,147,120,87,44,144,100,67,34,156\r\nP033,Product 033,Sales,114,110,145,108,104,143,146,105,151,94,138,141\r\nP033,Product 033,Inventory_level,869,759,614,506,402,259,113,1062,911,817,679,538\r\nP034,Product 034,Sales,139,154,137,164,189,178,183,180,209,126,153,211\r\nP034,Product 034,Inventory_level,599,445,308,144,868,690,507,327,118,1139,986,775\r\nP035,Product 035,Sales,74,59,70,87,98,69,86,78,73,88,84,80\r\nP035,Product 035,Inventory_level,390,331,261,174,76,7,602,524,451,363,279,199\r\nP036,Product 036,Sales,28,34,47,33,40,29,40,36,41,39,36,39\r\nP036,Product 036,Inventory_level,99,65,18,133,93,64,24,136,95,56,20,139\r\nP037,Product 037,Sales,376,100,167,74,235,201,51,417,165,673,264,199\r\nP037,Product 037,Inventory_level,4,1145,978,904,669,468,417,0,1165,492,228,1867\r\nP038,Product 038,Sales,434,230,137,231,47,57,121,64,69,102,255,175\r\nP038,Product 038,Inventory_level,230,0,1621,1390,1343,1286,1165,1101,1032,930,675,500\r\nP039,Product 039,Sales,139,186,86,100,94,144,105,105,130,86,160,165\r\nP039,Product 039,Inventory_level,802,616,530,430,336,192,87,899,769,683,523,358\r\nP040,Product 040,Sales,223,116,80,68,74,14,74,57,61,53,14,52\r\nP040,Product 040,Inventory_level,116,0,1034,966,892,878,804,747,686,633,619,567\r\nP041,Product 041,Sales,56,66,59,54,63,87,66,76,63,49,63,55\r\nP041,Product 041,Inventory_level,217,151,92,38,276,189,123,47,369,320,257,202\r\nP042,Product 042,Sales,61,67,78,29,93,73,88,44,86,89,45,67\r\nP042,Product 042,Inventory_level,498,431,353,324,231,158,70,26,285,196,151,84\r\nP043,Product 043,Sales,127,165,137,157,117,140,133,156,145,139,125,156\r\nP043,Product 043,Inventory_level,931,766,629,472,355,215,82,970,825,686,561,405\r\nP044,Product 044,Sales,80,77,50,61,288,91,88,259,65,125,60,64\r\nP044,Product 044,Inventory_level,39,450,400,339,51,759,671,412,347,222,162,98\r\nP045,Product 045,Sales,55,42,45,37,33,26,40,33,36,39,29,48\r\nP045,Product 045,Inventory_level,142,100,55,18,237,211,171,138,102,63,34,195\r\nP046,Product 046,Sales,69,100,134,68,51,223,92,102,110,56,148,112\r\nP046,Product 046,Inventory_level,291,191,57,700,649,426,334,232,122,66,547,435\r\nP047,Product 047,Sales,157,159,229,682,228,927,162,217,80,192,107,124\r\nP047,Product 047,Inventory_level,204,911,682,0,1574,647,485,268,188,611,504,380\r\nP048,Product 048,Sales,116,354,107,51,49,219,52,89,42,95,135,44\r\nP048,Product 048,Inventory_level,53,34,631,580,531,312,260,171,129,34,201,157\r\nP049,Product 049,Sales,82,66,61,70,94,89,92,74,82,70,57,52\r\nP049,Product 049,Inventory_level,183,117,56,476,382,293,201,127,45,557,500,448\r\nP050,Product 050,Sales,32,32,36,24,30,40,40,49,32,33,29,26\r\nP050,Product 050,Inventory_level,122,90,54,30,0,143,103,54,22,233,204,178\r\nP051,Product 051,Sales,26,29,42,34,36,30,25,33,31,43,30,34\r\nP051,Product 051,Inventory_level,125,96,54,20,233,203,178,145,114,71,41,7\r\nP052,Product 052,Sales,42,54,41,53,54,76,53,67,48,39,39,41\r\nP052,Product 052,Inventory_level,283,229,188,135,81,5,444,377,329,290,251,210\r\nP053,Product 053,Sales,49,58,65,51,63,69,69,79,68,56,48,54\r\nP053,Product 053,Inventory_level,24,218,153,102,39,270,201,122,54,362,314,260\r\nP054,Product 054,Sales,78,80,68,77,103,99,83,87,92,84,69,76\r\nP054,Product 054,Inventory_level,510,430,362,285,182,83,0,747,655,571,502,426\r\nP055,Product 055,Sales,51,80,62,76,75,87,66,67,87,85,73,76\r\nP055,Product 055,Inventory_level,498,418,356,280,205,118,52,596,509,424,351,275\r\nP056,Product 056,Sales,205,187,191,145,429,258,211,187,314,194,226,283\r\nP056,Product 056,Inventory_level,1633,1446,1255,1110,681,423,212,25,1025,831,605,322\r\nP057,Product 057,Sales,54,86,79,57,57,67,62,65,72,64,80,74\r\nP057,Product 057,Inventory_level,55,277,198,141,84,17,260,195,123,59,316,242\r\nP058,Product 058,Sales,113,135,129,110,149,145,141,123,150,123,116,96\r\nP058,Product 058,Inventory_level,336,201,72,467,318,173,32,491,341,218,102,527\r\nP059,Product 059,Sales,83,72,58,92,63,46,53,70,61,66,76,88\r\nP059,Product 059,Inventory_level,388,316,258,166,103,57,410,340,279,213,137,49\r\nP060,Product 060,Sales,140,194,159,191,161,210,180,194,167,158,162,171\r\nP060,Product 060,Inventory_level,587,393,234,43,972,762,582,388,221,63,940,769\r\nP061,Product 061,Sales,33,37,32,35,43,25,33,34,36,32,37,38\r\nP061,Product 061,Inventory_level,219,182,150,115,72,47,14,255,219,187,150,112\r\nP062,Product 062,Sales,49,43,38,55,55,72,80,70,63,46,59,60\r\nP062,Product 062,Inventory_level,30,220,182,127,72,0,226,156,93,47,287,227\r\nP063,Product 063,Sales,112,143,137,129,120,140,168,188,156,115,121,140\r\nP063,Product 063,Inventory_level,822,679,542,413,293,153,1029,841,685,570,449,309\r\nP064,Product 064,Sales,59,67,88,74,67,80,92,97,60,71,74,80\r\nP064,Product 064,Inventory_level,409,342,254,180,113,33,533,436,376,305,231,151\r\nP065,Product 065,Sales,111,112,107,121,130,166,165,125,145,96,116,144\r\nP065,Product 065,Inventory_level,607,495,388,267,137,570,405,280,135,766,650,506\r\nP066,Product 066,Sales,121,76,94,98,126,81,84,80,53,132,98,46\r\nP066,Product 066,Inventory_level,851,775,681,583,457,376,292,212,159,27,462,416\r\nP067,Product 067,Sales,95,90,140,101,120,170,136,155,125,109,133,107\r\nP067,Product 067,Inventory_level,282,192,52,385,265,95,482,327,202,93,481,374\r\nP068,Product 068,Sales,251,193,309,25,114,109,104,127,76,92,53,75\r\nP068,Product 068,Inventory_level,719,526,217,192,78,866,762,635,559,467,414,339\r\nP069,Product 069,Sales,108,84,103,77,87,109,92,88,85,121,94,105\r\nP069,Product 069,Inventory_level,465,381,278,201,114,5,464,376,291,170,76,574\r\nP070,Product 070,Sales,103,137,117,142,136,238,214,195,146,159,157,162\r\nP070,Product 070,Inventory_level,650,513,396,254,118,672,458,263,117,1071,914,752\r\nP071,Product 071,Sales,140,137,106,97,125,115,110,101,100,112,124,108\r\nP071,Product 071,Inventory_level,97,537,431,334,209,94,549,448,348,236,112,4\r\nP072,Product 072,Sales,135,176,111,107,110,166,133,117,115,127,139,133\r\nP072,Product 072,Inventory_level,505,329,218,111,1,495,362,245,130,3,584,451\r\nP073,Product 073,Sales,197,12,106,200,64,100,104,104,115,110,28,99\r\nP073,Product 073,Inventory_level,594,582,476,276,212,112,8,352,237,127,99,0\r\nP074,Product 074,Sales,39,52,59,48,53,57,67,68,40,39,40,47\r\nP074,Product 074,Inventory_level,91,39,218,170,117,60,259,191,151,112,72,25\r\nP075,Product 075,Sales,49,61,59,60,60,64,59,34,58,57,51,41\r\nP075,Product 075,Inventory_level,148,87,28,196,136,72,13,224,166,109,58,240\r\nP076,Product 076,Sales,97,98,92,97,116,135,101,129,93,104,117,111\r\nP076,Product 076,Inventory_level,664,566,474,377,261,126,25,838,745,641,524,413\r\nP077,Product 077,Sales,31,22,32,34,34,31,37,30,30,17,21,31\r\nP077,Product 077,Inventory_level,28,6,136,102,68,37,0,150,120,103,82,51\r\nP078,Product 078,Sales,68,37,32,22,50,44,40,25,79,141,24,11\r\nP078,Product 078,Inventory_level,32,174,142,120,70,26,143,118,39,92,68,57\r\nP079,Product 079,Sales,48,54,37,37,46,44,42,41,40,55,52,43\r\nP079,Product 079,Inventory_level,222,168,131,94,48,4,304,263,223,168,116,73\r\nP080,Product 080,Sales,70,40,39,42,225,63,56,72,30,46,88,57\r\nP080,Product 080,Inventory_level,465,425,386,344,119,56,0,565,535,489,401,344\r\nP081,Product 081,Sales,27,29,31,40,28,37,37,39,30,37,33,35\r\nP081,Product 081,Inventory_level,62,33,225,185,157,120,83,44,14,226,193,158\r\nP082,Product 082,Sales,146,199,114,234,409,121,352,166,235,107,197,82\r\nP082,Product 082,Inventory_level,273,74,1585,1351,942,821,469,303,68,1973,1776,1694\r\nP083,Product 083,Sales,111,109,107,100,102,170,142,154,152,116,86,85\r\nP083,Product 083,Inventory_level,710,601,494,394,292,122,977,823,671,555,469,384\r\nP084,Product 084,Sales,190,145,622,503,315,411,267,201,82,242,209,151\r\nP084,Product 084,Inventory_level,1,1125,503,0,2415,2004,1737,1536,1454,1212,1003,852\r\nP085,Product 085,Sales,190,178,134,150,115,126,142,108,137,137,141,187\r\nP085,Product 085,Inventory_level,771,593,459,309,194,68,971,863,726,589,448,261\r\nP086,Product 086,Sales,146,132,120,122,106,132,159,134,126,142,122,127\r\nP086,Product 086,Inventory_level,388,256,136,948,842,710,551,417,291,149,968,841\r\nP087,Product 087,Sales,278,208,191,132,212,262,257,275,291,182,285,270\r\nP087,Product 087,Inventory_level,647,439,248,1020,808,546,289,991,700,518,233,975\r\nP088,Product 088,Sales,37,44,46,41,49,47,46,48,61,43,57,52\r\nP088,Product 088,Inventory_level,167,123,77,36,253,206,160,112,51,8,257,205\r\nP089,Product 089,Sales,24,38,28,32,35,31,31,42,36,38,33,36\r\nP089,Product 089,Inventory_level,93,55,27,118,83,52,21,111,75,37,4,112\r\nP090,Product 090,Sales,70,62,58,67,78,68,62,72,63,66,56,84\r\nP090,Product 090,Inventory_level,221,159,101,34,270,202,140,68,5,268,212,128\r\nP091,Product 091,Sales,42,39,37,36,78,48,67,79,65,48,48,18\r\nP091,Product 091,Inventory_level,316,277,240,204,126,78,11,449,384,336,288,270\r\nP092,Product 092,Sales,55,54,76,44,290,123,43,72,93,83,52,80\r\nP092,Product 092,Inventory_level,464,410,334,290,0,425,382,310,217,134,82,2\r\nP093,Product 093,Sales,49,37,40,28,25,42,42,32,39,43,37,34\r\nP093,Product 093,Inventory_level,167,130,90,62,37,183,141,109,70,27,219,185\r\nP094,Product 094,Sales,117,97,108,95,99,146,117,156,115,107,110,110\r\nP094,Product 094,Inventory_level,230,133,25,362,263,117,0,387,272,165,55,390\r\nP095,Product 095,Sales,106,114,102,81,56,104,136,121,85,75,75,85\r\nP095,Product 095,Inventory_level,225,111,9,358,302,198,62,337,252,177,102,17\r\nP096,Product 096,Sales,47,66,65,69,67,92,81,108,62,56,62,46\r\nP096,Product 096,Inventory_level,237,171,106,37,239,147,66,280,218,162,100,54\r\nP097,Product 097,Sales,87,84,81,86,92,89,58,79,87,83,76,81\r\nP097,Product 097,Inventory_level,58,348,267,181,89,0,392,313,226,143,67,397\r\nP098,Product 098,Sales,62,75,67,73,72,53,63,72,76,70,47,68\r\nP098,Product 098,Inventory_level,255,180,113,40,402,349,286,214,138,68,462,394\r\nP099,Product 099,Sales,66,109,89,86,115,64,139,83,171,115,67,150\r\nP099,Product 099,Inventory_level,318,209,120,476,361,297,158,75,382,267,200,50\r\nP100,Product 100,Sales,102,63,55,60,69,105,67,84,60,104,177,56\r\nP100,Product 100,Inventory_level,161,98,43,427,358,253,186,102,42,363,186,130\r\nP101,Product 101,Sales,47,62,78,63,82,47,58,62,58,68,50,51\r\nP101,Product 101,Inventory_level,367,305,227,164,82,35,494,432,374,306,256,205\r\nP102,Product 102,Sales,322,140,63,175,66,155,52,93,69,150,374,88\r\nP102,Product 102,Inventory_level,325,185,122,1177,1111,956,904,811,742,592,218,130\r\nP103,Product 103,Sales,138,164,137,164,175,163,156,148,127,148,169,121\r\nP103,Product 103,Inventory_level,663,499,362,198,23,655,499,351,224,76,615,494\r\nP104,Product 104,Sales,158,186,123,136,139,125,123,142,161,121,157,161\r\nP104,Product 104,Inventory_level,557,371,248,112,718,593,470,328,167,759,602,441\r\nP105,Product 105,Sales,35,37,46,43,28,48,42,34,38,37,32,40\r\nP105,Product 105,Inventory_level,127,90,44,279,251,203,161,127,89,52,278,238\r\nP106,Product 106,Sales,50,47,41,53,53,70,66,64,43,46,58,50\r\nP106,Product 106,Inventory_level,152,105,64,11,289,219,153,89,46,0,304,254\r\nP107,Product 107,Sales,36,26,31,31,32,44,37,56,38,30,33,37\r\nP107,Product 107,Inventory_level,149,123,92,61,29,175,138,82,44,14,232,195\r\nP108,Product 108,Sales,56,53,54,74,60,90,95,86,56,48,70,55\r\nP108,Product 108,Inventory_level,331,278,224,150,90,0,363,277,221,173,103,48\r\nP109,Product 109,Sales,83,88,105,60,81,78,56,84,61,78,75,83\r\nP109,Product 109,Inventory_level,265,177,72,12,270,192,136,52,283,205,130,47\r\nP110,Product 110,Sales,57,71,57,59,65,69,67,65,67,62,69,61\r\nP110,Product 110,Inventory_level,176,105,48,238,173,104,37,243,176,114,45,250\r\nP111,Product 111,Sales,243,261,233,202,232,211,197,227,212,173,236,180\r\nP111,Product 111,Inventory_level,1715,1454,1221,1019,787,576,379,152,1637,1464,1228,1048\r\nP112,Product 112,Sales,56,59,80,52,52,48,65,51,56,40,45,40\r\nP112,Product 112,Inventory_level,187,128,48,452,400,352,287,236,180,140,95,55\r\nP113,Product 113,Sales,36,29,38,39,40,34,28,28,29,35,34,34\r\nP113,Product 113,Inventory_level,73,44,253,214,174,140,112,84,55,20,205,171\r\nP114,Product 114,Sales,84,102,87,83,113,107,103,121,98,90,89,68\r\nP114,Product 114,Inventory_level,678,576,489,406,293,186,83,829,731,641,552,484\r\nP115,Product 115,Sales,87,85,84,87,77,63,71,88,87,92,77,83\r\nP115,Product 115,Inventory_level,372,287,203,116,39,476,405,317,230,138,61,492\r\nP116,Product 116,Sales,108,101,81,121,123,131,131,118,96,103,88,103\r\nP116,Product 116,Inventory_level,272,171,90,357,234,103,474,356,260,157,69,350\r\nP117,Product 117,Sales,100,88,96,66,90,108,118,134,105,85,97,97\r\nP117,Product 117,Inventory_level,250,162,66,0,259,151,33,323,218,133,36,324\r\nP118,Product 118,Sales,88,96,92,75,91,84,86,87,88,84,86,79\r\nP118,Product 118,Inventory_level,391,295,203,128,37,470,384,297,209,125,39,478\r\nP119,Product 119,Sales,27,31,28,31,31,29,26,36,31,28,31,26\r\nP119,Product 119,Inventory_level,53,22,193,162,131,102,76,40,9,202,171,145\r\nP120,Product 120,Sales,67,69,57,50,41,50,48,49,56,50,62,51\r\nP120,Product 120,Inventory_level,71,2,198,148,107,57,198,149,93,43,191,140\r\nP121,Product 121,Sales,190,74,44,47,22,51,62,291,53,51,110,77\r\nP121,Product 121,Inventory_level,0,731,687,640,618,567,505,214,161,110,0,929\r\nP122,Product 122,Sales,56,51,59,46,60,60,61,66,66,52,54,73\r\nP122,Product 122,Inventory_level,326,275,216,170,110,50,432,366,300,248,194,121\r\nP123,Product 123,Sales,57,56,52,54,52,52,53,51,41,70,55,65\r\nP123,Product 123,Inventory_level,124,68,272,218,166,114,61,222,181,111,56,214\r\nP124,Product 124,Sales,87,68,89,79,89,123,98,100,81,123,69,85\r\nP124,Product 124,Inventory_level,593,525,436,357,268,145,47,779,698,575,506,421\r\nP125,Product 125,Sales,94,124,88,103,87,86,100,95,87,100,89,140\r\nP125,Product 125,Inventory_level,497,373,285,182,95,662,562,467,380,280,191,51\r\nP126,Product 126,Sales,52,50,41,24,36,35,39,35,29,36,44,33\r\nP126,Product 126,Inventory_level,6,295,254,230,194,159,120,85,56,20,212,179\r\nP127,Product 127,Sales,166,167,131,0,266,311,134,140,73,262,99,601\r\nP127,Product 127,Inventory_level,564,397,266,266,0,1511,1377,1237,1164,902,803,202\r\nP128,Product 128,Sales,102,102,108,88,114,123,112,127,94,104,76,115\r\nP128,Product 128,Inventory_level,218,116,747,659,545,422,310,183,89,764,688,573\r\nP129,Product 129,Sales,88,100,105,90,102,131,177,147,115,85,82,83\r\nP129,Product 129,Inventory_level,528,428,323,233,131,0,372,225,110,25,523,440\r\nP130,Product 130,Sales,35,28,26,24,28,24,40,32,24,33,28,31\r\nP130,Product 130,Inventory_level,93,65,39,15,93,69,29,122,98,65,37,6\r\nP131,Product 131,Sales,106,82,108,87,85,135,111,115,93,93,85,69\r\nP131,Product 131,Inventory_level,82,0,567,480,395,260,149,34,787,694,609,540\r\nP132,Product 132,Sales,274,67,51,91,82,46,48,82,186,77,85,91\r\nP132,Product 132,Inventory_level,280,213,162,71,409,363,315,233,47,606,521,430\r\nP133,Product 133,Sales,105,103,92,114,146,181,201,154,149,113,136,88\r\nP133,Product 133,Inventory_level,744,641,549,435,289,108,793,639,490,377,241,153\r\nP134,Product 134,Sales,155,278,184,155,189,160,173,178,189,132,219,205\r\nP134,Product 134,Inventory_level,994,716,532,377,188,1439,1266,1088,899,767,548,343\r\nP135,Product 135,Sales,117,222,184,144,124,152,129,143,130,172,158,228\r\nP135,Product 135,Inventory_level,539,317,133,1036

In [ ]:
import pandas as pd

In [ ]:
sales_test = pd.read_csv('sales_test_2025.csv')

In [ ]:
sales_test.head()
sales_test.dtypes

ProductID       object
Product_name    object
Type            object
2025-01          int64
2025-02          int64
2025-03          int64
2025-04          int64
2025-05          int64
2025-06          int64
2025-07          int64
2025-08          int64
2025-09          int64
2025-10          int64
2025-11          int64
2025-12          int64
dtype: object

In [ ]:
sales_test.head()

,ProductID,Product_name,Type,2025-01,2025-02,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12
0,P001,Product 001,Sales,54,59,51,46,45,52,77,67,62,55,43,39
1,P001,Product 001,Inventory_level,202,143,92,46,1,237,160,93,31,392,349,310
2,P002,Product 002,Sales,30,30,31,37,41,40,30,35,38,37,43,32
3,P002,Product 002,Inventory_level,230,200,169,132,91,51,21,284,246,209,166,134
4,P003,Product 003,Sales,68,74,58,51,64,73,69,78,71,68,82,80

In [ ]:
#selezioniamo solo le righe sales

sales_only25 = sales_test [sales_test ['Type']== 'Sales']

In [ ]:
sales_only25.head()

,ProductID,Product_name,Type,2025-01,2025-02,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12
0,P001,Product 001,Sales,54,59,51,46,45,52,77,67,62,55,43,39
2,P002,Product 002,Sales,30,30,31,37,41,40,30,35,38,37,43,32
4,P003,Product 003,Sales,68,74,58,51,64,73,69,78,71,68,82,80
6,P004,Product 004,Sales,114,137,146,105,124,116,161,117,136,142,173,140
8,P005,Product 005,Sales,29,31,34,32,31,29,38,30,28,27,30,26

In [ ]:
#facciamo il melt e trasformiamo wide in long

sales_train_2025_long = sales_only25.melt (
id_vars = ['ProductID'],
value_vars = sales_only25.columns[3:],
var_name ='date' ,
value_name = 'quantity_sales_2025'
)

sales_train_2025_long.head()

  ProductID     date  quantity_sales_2025
0      P001  2025-01                   54
1      P002  2025-01                   30
2      P003  2025-01                   68
3      P004  2025-01                  114
4      P005  2025-01                   29

In [ ]:
# date problem

sales_train_2025_long ['date'] = pd.to_datetime(sales_train_2025_long  ['date'])

In [ ]:
sales_train_2025_long.rename(columns={'quantity_sales_2025': 'quantity_sales'}, inplace=True)

In [ ]:
print(sales_train_2025_long.dtypes)
print(sales_train_2025_long.head())

ProductID                 object
date              datetime64[ns]
quantity_sales             int64
dtype: object
  ProductID       date  quantity_sales
0      P001 2025-01-01              54
1      P002 2025-01-01              30
2      P003 2025-01-01              68
3      P004 2025-01-01             114
4      P005 2025-01-01              29

In [ ]:
sales_train_2025_long.to_csv('sales_train_2025_long.csv', index=False)

In [ ]:
from google.colab import files
files.download('sales_train_2025_long.csv')

In [ ]:

# I'm doing the same thing but with inventory

inventory_only25 = sales_test[ sales_test  ['Type']== 'Inventory_level']

In [ ]:
inventory_only25.head()

,ProductID,Product_name,Type,2025-01,2025-02,2025-03,2025-04,2025-05,2025-06,2025-07,2025-08,2025-09,2025-10,2025-11,2025-12
1,P001,Product 001,Inventory_level,202,143,92,46,1,237,160,93,31,392,349,310
3,P002,Product 002,Inventory_level,230,200,169,132,91,51,21,284,246,209,166,134
5,P003,Product 003,Inventory_level,350,276,218,167,103,30,277,199,128,60,344,264
7,P004,Product 004,Inventory_level,568,431,285,180,56,692,531,414,278,136,755,615
9,P005,Product 005,Inventory_level,152,121,87,55,24,159,121,91,63,36,150,124

In [ ]:


inventory_test_2025_long = inventory_only25.melt (
id_vars = [ 'ProductID'],
value_vars = inventory_only25.columns [3:],
var_name= 'date',
value_name= 'inventory_level'
)
inventory_test_2025_long.head()

  ProductID     date  inventory_level
0      P001  2025-01              202
1      P002  2025-01              230
2      P003  2025-01              350
3      P004  2025-01              568
4      P005  2025-01              152

In [ ]:


inventory_test_2025_long ['date'] = pd.to_datetime(inventory_test_2025_long  ['date'])

In [ ]:
inventory_test_2025_long.dtypes

ProductID                  object
date               datetime64[ns]
inventory_level             int64
dtype: object

In [ ]:
inventory_test_2025_long.to_csv('inventory_test_2025_long.csv', index=False)

In [ ]:
from google.colab import files
files.download('inventory_test_2025_long.csv')